version: '3.2'
services:
  paws:
    image: gcr.io/panoptes-survey/paws
    container_name: paws
    env_file: 
      - ${PANDIR}/env_file
    depends_on:
      - "config-server"        
      - "messaging"
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host            
    volumes:
      - pandir:/var/panoptes
volumes:
    pandir:
      driver: local
      driver_opts:
        type: none
        device: /var/panoptes
        o: bind